### ISSUE TITLE
Missing toggle icon in mobile view

### ISSUE THREAD

**Issue by rocksack** [rvalitov/widgetkit-popover-ex#9]
I'm using custom toggle icon in popover-ex. Everything's fine but in mobile-view the icons are gone... 😟
I think it's a general problem of the popover-widget. You can also see this, wenn you open the official Demo (popover) https://yootheme.com/widgetkit with your smartphone.

But the Yootheme-Support is not able to help me, because i use your (custom) Version.  :-(
So i hope, you can help me!?

How can i get the icons always visible?

Thank you!

**Comment by rocksack** [comment]
Meanwhile i got answer from Yootheme:
https://yootheme.com/support/question/124833#answer-390947

**Comment by rvalitov** [comment]
Hi! Yes, they give you a correct answer: it's not a bug, it's hidden by design. I'm not sure if it's a good idea to show the icons always, because I tried it in the past and it works bad: the screen of the mobile is too small while the icons are too big and can intersect, etc.

If you still want to make the icons visible, I can give you a much easier solution that specified by the Yootheme. You will not have to modify the code, just add some CSS overrides to your template.
